ALTER TABLE threads ADD COLUMN memory_extracted INTEGER NOT NULL DEFAULT 1;
ALTER TABLE memories ADD COLUMN kind TEXT NOT NULL DEFAULT 'fact';
ALTER TABLE memories ADD COLUMN explicit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE memories ADD COLUMN source_message_id TEXT;
ALTER TABLE memories ADD COLUMN observed_at DATETIME;
